config/routes.rb
Hmeter::Application.routes.draw do
  get "sessions/new"
  get "users/new"
  get "pages/home"
  get "pages/about"

  root :to => 'pages#home'
  
  resources :usertables
  resources :userinfos
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/about',   :to => 'pages#about'
  











end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  uname      :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
class User < ActiveRecord::Base
  has_many :usertables 		

  attr_accessor :password
  attr_accessible :uname, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :uname, :presence => true,
                    :length   => { :maximum => 20 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
			  :uniqueness => { :case_sensitive => false }
 
 # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/models/usertable.rb
# == Schema Information
#
# Table name: usertables
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  mood       :string(255)
#  created_at :datetime
#  updated_at :datetime



class Usertable < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
      user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      # Sign the user in and redirect to the user's show page.
      sign_in user
     redirect_to usertables_path
   #  redirect_to new_usertable_path
   #  redirect to user
    end
  end


 
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users
  # GET /users.json
  def index
    
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "Sign up"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end

  end

   def create
    @user = User.new(params[:user])
    
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Happy O'Meter!"
      redirect_to usertables_path
     # redirect_to new_usertable_path
     # redirect_to @user

     # # Handle a successful save.
     # session[:user_id] = @user.id
     # redirect_to new_usertable_path
     # redirect_to usertables_path 
    else
      @title = "Sign up"
      render 'new'
    end
  end

   def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Your mood was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/controllers/usertables_controller.rb
class UsertablesController < ApplicationController
  # GET /usertables
  # GET /usertables.json
  def index
   # @user = User.find_by_id(session[:remember_token])  
   # @user = User.find_by_id(cookies[:remember_token])

   # @user = User.find(session[:user_id])
   # @usertables = Usertable.find_all_by_user_id(@user.id)

   @user = current_user
   @usertables = Usertable.find_all_by_user_id(@user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usertables }
      
    end
  end

  # GET /usertables/1
  # GET /usertables/1.json
  def show
    @usertable = Usertable.find(params[:id])
   # @user = User.find(session[:user_id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usertable }
    end
  end

  # GET /usertables/new
  # GET /usertables/new.json
  def new
    @usertable = Usertable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usertable }
    end
  end

  # GET /usertables/1/edit
  def edit
    @usertable = Usertable.find(params[:id])
  end

  # POST /usertables
  # POST /usertables.json
  def create
    # @user = User.find(session[:user_id])
    # @usertable = Usertable.new(params[:usertable])
    # @usertable.user = @user

    @user = current_user
    @usertable = Usertable.new(params[:usertable])
    @usertable.user = @user

    respond_to do |format|
      if @usertable.save
        format.html { redirect_to @usertable, notice: 'Your mood was successfully saved.' }
        format.json { render json: @usertable, status: :created, location: @usertable }
      else
        format.html { render action: "new" }
        format.json { render json: @usertable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usertables/1
  # PUT /usertables/1.json
  def update
    @usertable = Usertable.find(params[:id])

    respond_to do |format|
      if @usertable.update_attributes(params[:usertable])
        format.html { redirect_to @usertable, notice: 'Your mood was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @usertable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertables/1
  # DELETE /usertables/1.json
  def destroy
    @usertable = Usertable.find(params[:id])
    @usertable.destroy

    respond_to do |format|
      format.html { redirect_to usertables_url }
      format.json { head :ok }
    end
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    @current_user = nil
  end

  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end
    
    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/userinfos_helper.rb
module UserinfosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usertables_helper.rb
module UsertablesHelper

end

app/views/layouts/ORIGapplication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy OMeter</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %> 
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %> 
</head>
<body>
<div class="container">
    <header>

       <%= image_tag("hmeter_logo_frompdf.png", :alt => "logo", :class => "round") %>
     

        <nav>
       
        <!--  <ul> -->
        <!--    <li><%= link_to "Home", '#' %></li>-->
        <!--    <li><%= link_to "Sign in", '#' %></li>-->
            <% if signed_in? %>
           <b>   <span style="float: right; "><%= link_to "Sign out", signout_path, :method => :delete %></span></b>
            <% end %>
            
        <!--  </ul> -->
        </nav>

          
      </header>
  
    <section class="round">
      <%= yield %>
    </section>

    <%= debug(params) if Rails.env.development? %>
  
</div>

<footer>
  <div class="container">
    Sawas Inc. <br>
    Sponsored by: GRRR Corporations<br>
    Jan 2012
</footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Happy OMeter</title>
  <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>
</head>
<body>
<div class="container">
    <header>

       <%= image_tag("hmeter_logo_frompdf.png", :alt => "logo", :class => "round") %>
     

        <nav>
       
        <!--  <ul> -->
        <!--    <li><%= link_to "Home", '#' %></li>-->
        <!--    <li><%= link_to "Sign in", '#' %></li>-->
            <% if signed_in? %>
           <b>   <span style="float: right; "><%= link_to "Sign out", signout_path, :method => :delete %></span></b>
            <% end %>
            
        <!--  </ul> -->
        </nav>

          
      </header>
  
    <section class="round">
      <%= yield %>
    </section>

    <%= debug(params) if Rails.env.development? %>
  
</div>

<footer>
  <div class="container">
    Sawas Inc. <br>
    Sponsored by: GRRR Corporations<br>
    Jan 2012
</footer>

</body>
</html>

app/views/pages/about.html.erb
  <h2>About</h2>

  <p>The Happy O'Meter is the brainchild of Sawas Inc, created by an imaginative girl who was inspired 
  one summer day in between Grade 6 and 7. The Happy O'Meter allows you to record your 
  mood at any time and tracks it for you in an easy-to-read table.</p>

  <br>
  <p>Many thanks go out to coding wonders Miika Pihjala, Varun Singh, Karri Saarinen, Vesa Vänksä, Michael Hartl, Gregg Pollack and 
  the c<>de school, and the benevolent geniuses at stackoverflow, without whom The Happy O'Meter would 
  be stuck in erb. And to Rails Girls Helsinki, for believing in the rails programmer in all of us!


<h3><%= link_to "Home", root_path %></h3>

app/views/pages/home.html.erb
<!--<h1>Pages#home</h1>-->
<!--<p>Find me in app/views/pages/home.html.erb</p>-->

<ul> 
<h5><span style="float: right; "><%= link_to "About", about_path %></span></h5>
</ul>


<!--<h1>Welcome to The Happy OMeter!</h1>-->
<!--<p>-->
<!--  This is the home page for the-->
<!--  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>-->
<!--  sample application.-->
<!--</p>-->

<h2>Welcome! Please <%= link_to "Sign in", signin_path %></h2>
<br>
New user? <h3><%= link_to "Sign up now!",signup_path, :class => "signup_button" %></h3>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/userinfos/_form.html.erb
<%= form_for(@userinfo) do |f| %>
  <% if @userinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userinfo.errors.count, "error") %> prohibited this userinfo from being saved:</h2>

      <ul>
      <% @userinfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mood %><br />
    <%= f.text_area :mood %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userinfos/edit.html.erb
<h1>Editing userinfo</h1>

<%= render 'form' %>

<%= link_to 'Show', @userinfo %> |
<%= link_to 'Back', userinfos_path %>

app/views/userinfos/index.html.erb
<h1>Listing userinfos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mood</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @userinfos.each do |userinfo| %>
  <tr>
    <td><%= userinfo.name %></td>
    <td><%= userinfo.mood %></td>
    <td><%= link_to 'Show', userinfo %></td>
    <td><%= link_to 'Edit', edit_userinfo_path(userinfo) %></td>
    <td><%= link_to 'Destroy', userinfo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Userinfo', new_userinfo_path %>

app/views/userinfos/new.html.erb
<h1>New userinfo</h1>

<%= render 'form' %>

<%= link_to 'Back', userinfos_path %>

app/views/userinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @userinfo.name %>
</p>

<p>
  <b>Mood:</b>
  <%= @userinfo.mood %>
</p>


<%= link_to 'Edit', edit_userinfo_path(@userinfo) %> |
<%= link_to 'Back', userinfos_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>


<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label "Name" %><br />
    <%= f.text_field :uname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/usertables/_form.html.erb
<%= form_for(@usertable) do |f| %>
  <% if @usertable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertable.errors.count, "error") %> prohibited this usertable from being saved:</h2>

      <ul>
      <% @usertable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      

  <!-- <div class="field">-->
  <!--<%= f.label :name %><br/>-->
  <!--<%= f.text_field :name %>-->
  <!--</div>-->


<!--  this was the original way of inputing mood--write mood in a text box -->
<!--  this has now been replaced by a list of radio buttons (next block)   -->
<!--  <div class="field"> 		-->
<!--  <%= f.label :mood %><br/>	-->
<!--  <%= f.text_area :mood %> 	-->
<!--  </div>				-->

<style type="text/css">
span.white {color:white;font-weight:bold}
</style>

  <div class="form-field">
    <%= f.label :mood %><br/>
    
  <!--  <ul class="inputs-lists"> -->
        <%= f.radio_button :mood, "Overjoyed" %><span> Overjoyed<span class="white">..........</span>
        <%= f.radio_button :mood, "Happy" %><span> Happy<span class="white">..........</span>
        <%= f.radio_button :mood, "Good Mood" %><span> Good Mood<span class="white">..........</span>
        <%= f.radio_button :mood, "Miserable" %><span> Miserable<span class="white">..........</span>
        <%= f.radio_button :mood, "Excited" %><span> Excited<span class="white">..........</span>
   <!-- </ul> -->
  </div>

  <div class="actions">
    <%= f.submit "Save" %>
  </div>

  <div>
<div>

</end>



<% end %>

app/views/usertables/edit.html.erb
<h2>Hello, <%= current_user.uname %>! What is your mood? </h2>

<%= render 'form' %>

<!--<%= link_to 'Show', @usertable %> | -->
<!--<%= link_to 'Return to the Happy OMeter', usertables_path %> -->

app/views/usertables/index.html.erb
<!--<h1>The Happy O'Meter</h1>-->

<!--<%= link_to 'What is your mood?', new_usertable_path, :style => "font-size:22px;font-weight:bold;" %><p>-->


<p><h3><%= Date.today.to_formatted_s(:long) %></h3></p>


<h3> Hello, <%= current_user.uname %>! Add a <u><%= link_to 'new mood', new_usertable_path %></u></h3> 
<p>

<!--begin my table-->
<table border="1" 
cellpadding="10">
<tr>
  <th>Overjoyed</td>
  <th>Happy</td>
  <th>Good Mood</td>
  <th>Miserable</td>
  <th>Excited</td>
</tr>   



<% @usertables.each do |usertable| %>
  <tr>
  <% if usertable.mood == "Overjoyed" %>    
    <td><%= current_user.uname %>&nbsp;&nbsp;<%= link_to 'Delete   ', usertable, confirm: 'Are you sure?', method: :delete %><%= link_to 'Edit', edit_usertable_path(usertable)%></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
<% elsif usertable.mood == "Happy" %>
    <td></td>
    <td><%= current_user.uname %>&nbsp;&nbsp;<%= link_to 'Delete   ', usertable, confirm: 'Are you sure?', method: :delete %><%= link_to 'Edit', edit_usertable_path(usertable)%></td>
    <td></td>
    <td></td>
    <td></td>
  <% elsif usertable.mood == "Good Mood" %>
    <td></td>
    <td></td>
    <td><%= current_user.uname %>&nbsp;&nbsp;<%= link_to 'Delete   ', usertable, confirm: 'Are you sure?', method: :delete %><%= link_to 'Edit', edit_usertable_path(usertable)%></td>
    <td></td>
    <td></td>
  <% elsif usertable.mood == "Miserable" %>
    <td></td>
    <td></td>
    <td></td>
    <td><%= current_user.uname %>&nbsp;&nbsp;<%= link_to 'Delete   ', usertable, confirm: 'Are you sure?', method: :delete %><%= link_to 'Edit', edit_usertable_path(usertable)%></td>  
    <td></td>
  <% elsif usertable.mood == "Excited" %>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><%= current_user.uname %>&nbsp;&nbsp;<%= link_to 'Delete   ', usertable, confirm: 'Are you sure?', method: :delete %><%= link_to 'Edit', edit_usertable_path(usertable)%></td>  

  <% end %>  
  </tr>
<% end %>

</table>
<!--end my table-->

<br>
<br>

<!--<table>-->
<!--  <tr>-->
<!--    <th>Name</th>-->
<!--    <th>Mood</th>-->
<!--    <th></th>-->
<!--    <th></th>-->
<!--    <th></th>-->
<!--  </tr>-->

<!--<% @usertables.each do |usertable| %>-->
<!--  <tr>-->
<!--    <td><%= usertable.name %></td>-->
<!--    <td><%= usertable.mood %></td>-->
<!--    <td><%= link_to 'Show', usertable %></td>-->
<!--    <td><%= link_to 'Edit', edit_usertable_path(usertable) %></td>-->
<!--    <td><%= link_to 'Destroy', usertable, confirm: 'Are you sure?', method: :delete %></td>-->
<!--  </tr>-->
<!--<% end %>-->
<!--</table>-->

<br />





app/views/usertables/karri_form.html.erb
<%= form_for(@usertable) do |f| %>
  <% if @usertable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertable.errors.count, "error") %> prohibited this usertable from being saved:</h2>

      <ul>
      <% @usertable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

<!--  this was the original way of inputing mood--write mood in a text box -->
<!--  this has now been replaced by a list of radio buttons (next block)   -->
<!--  <div class="field"> 		-->
<!--  <%= f.label :mood %><br/>	-->
<!--  <%= f.text_area :mood %> 	-->
<!--  </div>				-->

  <div class="field">
    <%= f.label :mood %><br/>
    
    <ul class="inputs-lists">
        <li><label><%= f.radio_button :mood, "Overjoyed" %><span>Overjoyed</span></label></li>
        <li><label><%= f.radio_button :mood, "Happy" %><span>Happy</span></label></li>
        <li><label><%= f.radio_button :mood, "Good Mood" %><span>Good Mood</span></label></li>
        <li><label><%= f.radio_button :mood, "Miserable" %><span>Miserable</span></label></li>
        <li><label><%= f.radio_button :mood, "Excited" %><span>Excited</span></label></li>
    </ul>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

  <div>
<div>

</end>



<% end %>

app/views/usertables/new.html.erb
<h3> Hello, <%= current_user.uname %>! How are you feeling today? </h3>

<%= render 'form' %>

<!--<%= link_to 'Go to Happy OMeter', usertables_path, :style => "font-size:22px;font-weight:bold;" %>-->

app/views/usertables/orig_form.html.erb
<%= form_for(@usertable) do |f| %>
  <% if @usertable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertable.errors.count, "error") %> prohibited this usertable from being saved:</h2>

      <ul>
      <% @usertable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

<!--  this was the original way of inputing mood--write mood in a text box -->
<!--  this has now been replaced by a list of radio buttons (next block)   -->
<!--  <div class="field"> 		-->
<!--  <%= f.label :mood %><br/>	-->
<!--  <%= f.text_area :mood %> 	-->
<!--  </div>				-->

  <div class="field">
    <%= f.label :mood %><br/>
    <%= f.radio_button :mood, "Overjoyed" %><%= f.label :mood, "Overjoyed" %><br />
    <%= f.radio_button :mood, "Happy" %><%= f.label :mood, "Happy" %><br />
    <%= f.radio_button :mood, "Good Mood" %><%= f.label :mood, "Good Mood" %><br />
    <%= f.radio_button :mood, "Miserable" %><%= f.label :mood, "Miserable" %><br />
    <%= f.radio_button :mood, "Excited" %><%= f.label :mood, "Excited" %><br />
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

  <div>
<div>

</end>



<% end %>

app/views/usertables/show.html.erb
<p id="notice"><%= notice %></p>

  

<p>
  <b>Mood:</b>
  <%= @usertable.mood %>
</p>

<br>
<%= link_to 'Edit', edit_usertable_path(@usertable) %> |
<%= link_to 'Return to the Happy OMeter', usertables_path %>